In [ ]:
import pandas as pd 
import get_journey_sncf_now as gjn


df = gjn.get_OD_now(ville_origine='Bordeaux',nb_trajets=2,etranger=False,niveau_service=2,minutes_max=120)
df

In [ ]:
tab = pd.read_csv('Outputs/results_Bordeaux_20221213T135825.csv')
tab

In [6]:
import affichage_vol_dest as avd

tab2 =avd.vol_dest_api('BOD')
tab2

,id_x,flyFrom,code,cityFrom,cityCodeFrom,cityTo,cityCodeTo,countryFrom,countryTo,nightsInDest,...,new_ground,routing_priority,type,lat,lon,Tps_trajet,Tps_total,Tps_trajet_sec,Tps_total_sec,Distance
0,0498091e4b8c0000ed5716a5_0,BOD,CRL,Bordeaux,BOD,Brussels,BRU,"{'code': 'FR', 'name': 'France'}","{'code': 'BE', 'name': 'Belgium'}",None,...,False,0.0,airport,50.459167,4.453889,0 days 01:03:00,1 days 01:42:57.691555,3780,6120,735.8
1,0498032d4b8c000031670893_0,BOD,STN,Bordeaux,BOD,London,LON,"{'code': 'FR', 'name': 'France'}","{'code': 'GB', 'name': 'United Kingdom'}",None,...,False,0.0,airport,51.885000,0.235000,0 days 01:58:00,1 days 01:40:57.691555,7080,6000,787.8
2,049800ed4b8c0000e4b3e7cf_0,BOD,MRS,Bordeaux,BOD,Marseille,MRS,"{'code': 'FR', 'name': 'France'}","{'code': 'FR', 'name': 'France'}",None,...,False,0.0,airport,43.436667,5.215000,0 days 01:02:00,1 days 05:40:57.691555,3720,20400,497.8
3,04980ec84b8c0000126f31c7_0,BOD,TSF,Bordeaux,BOD,Venice,VCE,"{'code': 'FR', 'name': 'France'}","{'code': 'IT', 'name': 'Italy'}",None,...,False,0.0,airport,45.650833,12.197778,0 days 01:59:00,1 days 03:38:57.691555,7140,13080,1014.1
4,049809b24b8c0000e8d775ff_0,BOD,CIA,Bordeaux,BOD,Rome,ROM,"{'code': 'FR', 'name': 'France'}","{'code': 'IT', 'name': 'Italy'}",None,...,False,0.0,airport,41.798889,12.595000,0 days 02:00:00,0 days 22:37:57.691555,7200,81420,1126.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,0498057b4b8c00005fb3984f_0|0498057b4b8c00005fb...,BOD,ZRH,Bordeaux,BOD,ZÃ¼rich,ZRH,"{'code': 'FR', 'name': 'France'}","{'code': 'CH', 'name': 'Switzerland'}",None,...,False,0.0,airport,47.464722,8.549167,0 days 05:03:00,1 days 01:42:57.691555,18180,6120,770.9
81,04980e354b8c4b95511cdc9d_0|04980e354b8c4b95511...,BOD,LYS,Bordeaux,BOD,Lyon,LYS,"{'code': 'FR', 'name': 'France'}","{'code': 'FR', 'name': 'France'}",None,...,False,0.0,airport,45.725556,5.081111,0 days 01:01:00,0 days 22:42:57.691555,3660,81720,464.3
82,04980c654b8b00009d731fe9_0,BOD,CMN,Bordeaux,BOD,Casablanca,CAS,"{'code': 'FR', 'name': 'France'}","{'code': 'MA', 'name': 'Morocco'}",None,...,NaN,NaN,NaN,NaN,NaN,0 days 02:02:00,0 days 04:39:57.691555,7320,16740,NaN
83,049825c34b8c4ba0eb83a2b2_0|049825c34b8c4ba0eb8...,BOD,CDG,Bordeaux,BOD,Paris,PAR,"{'code': 'FR', 'name': 'France'}","{'code': 'FR', 'name': 'France'}",None,...,False,0.0,airport,49.009722,2.547778,0 days 01:57:00,1 days 03:37:57.691555,7020,13020,526.7
84,049803584b8c4ba83dff3ae3_0|049803584b8c4ba83df...,BOD,LIS,Bordeaux,BOD,Lisbon,LIS,"{'code': 'FR', 'name': 'France'}","{'code': 'PT', 'name': 'Portugal'}",None,...,False,0.0,airport,38.774167,-9.134167,0 days 03:04:00,0 days 19:42:57.691555,11040,70920,968.7

In [5]:
import time
t= time.localtime()
print(str(t.tm_mday)+'/'+str(t.tm_mon)+'/'+str(t.tm_year))

13/12/2022